// Dow Jones Industrial Average — 30 components
export const DJIA = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'AXP', name: 'American Express Co.' },
  { symbol: 'BA', name: 'Boeing Co.' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'CVX', name: 'Chevron Corp.' },
  { symbol: 'DIS', name: 'Walt Disney Co.' },
  { symbol: 'DOW', name: 'Dow Inc.' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.' },
  { symbol: 'HD', name: 'Home Depot Inc.' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'IBM', name: 'International Business Machines Corp.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'KO', name: 'Coca-Cola Co.' },
  { symbol: 'MCD', name: "McDonald's Corp." },
  { symbol: 'MMM', name: '3M Co.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corp.' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'SHW', name: 'Sherwin-Williams Co.' },
  { symbol: 'TRV', name: 'Travelers Companies Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
];

// NASDAQ-100 components
export const NASDAQ100 = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'ADI', name: 'Analog Devices Inc.' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'ADSK', name: 'Autodesk Inc.' },
  { symbol: 'AEP', name: 'American Electric Power Co.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'ANSS', name: 'ANSYS Inc.' },
  { symbol: 'APP', name: 'AppLovin Corp.' },
  { symbol: 'ARM', name: 'Arm Holdings plc' },
  { symbol: 'ASML', name: 'ASML Holding NV' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'AZN', name: 'AstraZeneca PLC' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'BKR', name: 'Baker Hughes Co.' },
  { symbol: 'CCEP', name: 'Coca-Cola Europacific Partners PLC' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'CDW', name: 'CDW Corp.' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corp.' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.' },
  { symbol: 'CPRT', name: 'Copart Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'CSGP', name: 'CoStar Group Inc.' },
  { symbol: 'CTAS', name: 'Cintas Corp.' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corp.' },
  { symbol: 'DASH', name: 'DoorDash Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'DXCM', name: 'DexCom Inc.' },
  { symbol: 'EA', name: 'Electronic Arts Inc.' },
  { symbol: 'EXC', name: 'Exelon Corp.' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.' },
  { symbol: 'FAST', name: 'Fastenal Co.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
  { symbol: 'ILMN', name: 'Illumina Inc.' },
  { symbol: 'INTC', name: 'Intel Corp.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'KHC', name: 'Kraft Heinz Co.' },
  { symbol: 'KLAC', name: 'KLA Corp.' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'LRCX', name: 'Lam Research Corp.' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'MNST', name: 'Monster Beverage Corp.' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corp.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.' },
  { symbol: 'NXPI', name: 'NXP Semiconductors NV' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'PAYX', name: 'Paychex Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.' },
  { symbol: 'ROST', name: 'Ross Stores Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corp.' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.' },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corp.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
];

// S&P 500 components
export const SP500 = [
  { symbol: 'A', name: 'Agilent Technologies Inc.' },
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'ACGL', name: 'Arch Capital Group Ltd.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'ADI', name: 'Analog Devices Inc.' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland Co.' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'ADSK', name: 'Autodesk Inc.' },
  { symbol: 'AEE', name: 'Ameren Corp.' },
  { symbol: 'AEP', name: 'American Electric Power Co.' },
  { symbol: 'AES', name: 'AES Corp.' },
  { symbol: 'AFL', name: 'Aflac Inc.' },
  { symbol: 'AIG', name: 'American International Group Inc.' },
  { symbol: 'AIZ', name: 'Assurant Inc.' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc.' },
  { symbol: 'ALB', name: 'Albemarle Corp.' },
  { symbol: 'ALGN', name: 'Align Technology Inc.' },
  { symbol: 'ALL', name: 'Allstate Corp.' },
  { symbol: 'ALLE', name: 'Allegion plc' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'AMCR', name: 'Amcor plc' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'AME', name: 'AMETEK Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'AMP', name: 'Ameriprise Financial Inc.' },
  { symbol: 'AMT', name: 'American Tower Corp.' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'ANET', name: 'Arista Networks Inc.' },
  { symbol: 'ANSS', name: 'ANSYS Inc.' },
  { symbol: 'AON', name: 'Aon plc' },
  { symbol: 'AOS', name: 'A. O. Smith Corp.' },
  { symbol: 'APA', name: 'APA Corp.' },
  { symbol: 'APD', name: 'Air Products and Chemicals Inc.' },
  { symbol: 'APH', name: 'Amphenol Corp.' },
  { symbol: 'APTV', name: 'Aptiv PLC' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities Inc.' },
  { symbol: 'ATO', name: 'Atmos Energy Corp.' },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc.' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'AVY', name: 'Avery Dennison Corp.' },
  { symbol: 'AWK', name: 'American Water Works Co. Inc.' },
  { symbol: 'AXP', name: 'American Express Co.' },
  { symbol: 'AZO', name: 'AutoZone Inc.' },
  { symbol: 'BA', name: 'Boeing Co.' },
  { symbol: 'BAC', name: 'Bank of America Corp.' },
  { symbol: 'BAX', name: 'Baxter International Inc.' },
  { symbol: 'BBWI', name: 'Bath & Body Works Inc.' },
  { symbol: 'BBY', name: 'Best Buy Co. Inc.' },
  { symbol: 'BDX', name: 'Becton Dickinson and Co.' },
  { symbol: 'BEN', name: 'Franklin Resources Inc.' },
  { symbol: 'BF-B', name: 'Brown-Forman Corp.' },
  { symbol: 'BG', name: 'Bunge Global SA' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'BIO', name: 'Bio-Rad Laboratories Inc.' },
  { symbol: 'BK', name: 'Bank of New York Mellon Corp.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'BKR', name: 'Baker Hughes Co.' },
  { symbol: 'BLDR', name: 'Builders FirstSource Inc.' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Co.' },
  { symbol: 'BR', name: 'Broadridge Financial Solutions Inc.' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc.' },
  { symbol: 'BRO', name: 'Brown & Brown Inc.' },
  { symbol: 'BSX', name: 'Boston Scientific Corp.' },
  { symbol: 'BWA', name: 'BorgWarner Inc.' },
  { symbol: 'BX', name: 'Blackstone Inc.' },
  { symbol: 'BXP', name: 'BXP Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'CAG', name: 'Conagra Brands Inc.' },
  { symbol: 'CAH', name: 'Cardinal Health Inc.' },
  { symbol: 'CARR', name: 'Carrier Global Corp.' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'CB', name: 'Chubb Ltd.' },
  { symbol: 'CBOE', name: 'Cboe Global Markets Inc.' },
  { symbol: 'CBRE', name: 'CBRE Group Inc.' },
  { symbol: 'CCI', name: 'Crown Castle Inc.' },
  { symbol: 'CCL', name: 'Carnival Corp.' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'CDW', name: 'CDW Corp.' },
  { symbol: 'CE', name: 'Celanese Corp.' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc.' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc.' },
  { symbol: 'CHD', name: 'Church & Dwight Co. Inc.' },
  { symbol: 'CHRW', name: 'C.H. Robinson Worldwide Inc.' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.' },
  { symbol: 'CI', name: 'Cigna Group' },
  { symbol: 'CINF', name: 'Cincinnati Financial Corp.' },
  { symbol: 'CL', name: 'Colgate-Palmolive Co.' },
  { symbol: 'CLX', name: 'Clorox Co.' },
  { symbol: 'CMCSA', name: 'Comcast Corp.' },
  { symbol: 'CME', name: 'CME Group Inc.' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.' },
  { symbol: 'CMI', name: 'Cummins Inc.' },
  { symbol: 'CMS', name: 'CMS Energy Corp.' },
  { symbol: 'CNC', name: 'Centene Corp.' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.' },
  { symbol: 'COF', name: 'Capital One Financial Corp.' },
  { symbol: 'COO', name: 'Cooper Companies Inc.' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'COR', name: 'Cencora Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.' },
  { symbol: 'CPAY', name: 'Corpay Inc.' },
  { symbol: 'CPB', name: 'Campbell Soup Co.' },
  { symbol: 'CPRT', name: 'Copart Inc.' },
  { symbol: 'CPT', name: 'Camden Property Trust' },
  { symbol: 'CRL', name: 'Charles River Laboratories International Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'CSGP', name: 'CoStar Group Inc.' },
  { symbol: 'CSX', name: 'CSX Corp.' },
  { symbol: 'CTAS', name: 'Cintas Corp.' },
  { symbol: 'CTLT', name: 'Catalent Inc.' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc.' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corp.' },
  { symbol: 'CTVA', name: 'Corteva Inc.' },
  { symbol: 'CVS', name: 'CVS Health Corp.' },
  { symbol: 'CVX', name: 'Chevron Corp.' },
  { symbol: 'CZR', name: 'Caesars Entertainment Inc.' },
  { symbol: 'D', name: 'Dominion Energy Inc.' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.' },
  { symbol: 'DAY', name: 'Dayforce Inc.' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc.' },
  { symbol: 'DE', name: 'Deere & Co.' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corp.' },
  { symbol: 'DFS', name: 'Discover Financial Services' },
  { symbol: 'DG', name: 'Dollar General Corp.' },
  { symbol: 'DGX', name: 'Quest Diagnostics Inc.' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.' },
  { symbol: 'DHR', name: 'Danaher Corp.' },
  { symbol: 'DIS', name: 'Walt Disney Co.' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'DOV', name: 'Dover Corp.' },
  { symbol: 'DOW', name: 'Dow Inc.' },
  { symbol: 'DPZ', name: "Domino's Pizza Inc." },
  { symbol: 'DRI', name: "Darden Restaurants Inc." },
  { symbol: 'DTE', name: 'DTE Energy Co.' },
  { symbol: 'DUK', name: 'Duke Energy Corp.' },
  { symbol: 'DVA', name: 'DaVita Inc.' },
  { symbol: 'DVN', name: 'Devon Energy Corp.' },
  { symbol: 'DXCM', name: 'DexCom Inc.' },
  { symbol: 'EA', name: 'Electronic Arts Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'ECL', name: 'Ecolab Inc.' },
  { symbol: 'ED', name: 'Consolidated Edison Inc.' },
  { symbol: 'EFX', name: 'Equifax Inc.' },
  { symbol: 'EIX', name: 'Edison International' },
  { symbol: 'EL', name: 'Estee Lauder Companies Inc.' },
  { symbol: 'EMN', name: 'Eastman Chemical Co.' },
  { symbol: 'EMR', name: 'Emerson Electric Co.' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.' },
  { symbol: 'EOG', name: 'EOG Resources Inc.' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
  { symbol: 'EQR', name: 'Equity Residential' },
  { symbol: 'EQT', name: 'EQT Corp.' },
  { symbol: 'ES', name: 'Eversource Energy' },
  { symbol: 'ESS', name: 'Essex Property Trust Inc.' },
  { symbol: 'ETN', name: 'Eaton Corp. plc' },
  { symbol: 'ETR', name: 'Entergy Corp.' },
  { symbol: 'EVRG', name: 'Evergy Inc.' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corp.' },
  { symbol: 'EXC', name: 'Exelon Corp.' },
  { symbol: 'EXPD', name: 'Expeditors International of Washington Inc.' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.' },
  { symbol: 'EXR', name: 'Extra Space Storage Inc.' },
  { symbol: 'F', name: 'Ford Motor Co.' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.' },
  { symbol: 'FAST', name: 'Fastenal Co.' },
  { symbol: 'FCNCA', name: 'First Citizens BancShares Inc.' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.' },
  { symbol: 'FDS', name: 'FactSet Research Systems Inc.' },
  { symbol: 'FDX', name: 'FedEx Corp.' },
  { symbol: 'FE', name: 'FirstEnergy Corp.' },
  { symbol: 'FFIV', name: 'F5 Inc.' },
  { symbol: 'FI', name: 'Fiserv Inc.' },
  { symbol: 'FICO', name: 'Fair Isaac Corp.' },
  { symbol: 'FIS', name: 'Fidelity National Information Services Inc.' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp' },
  { symbol: 'FLT', name: 'FleetCor Technologies Inc.' },
  { symbol: 'FMC', name: 'FMC Corp.' },
  { symbol: 'FOX', name: 'Fox Corp. Class B' },
  { symbol: 'FOXA', name: 'Fox Corp. Class A' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust' },
  { symbol: 'FSLR', name: 'First Solar Inc.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'FTV', name: 'Fortive Corp.' },
  { symbol: 'GD', name: 'General Dynamics Corp.' },
  { symbol: 'GDDY', name: 'GoDaddy Inc.' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc.' },
  { symbol: 'GEN', name: 'Gen Digital Inc.' },
  { symbol: 'GEV', name: 'GE Vernova Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'GIS', name: 'General Mills Inc.' },
  { symbol: 'GL', name: 'Globe Life Inc.' },
  { symbol: 'GLW', name: 'Corning Inc.' },
  { symbol: 'GM', name: 'General Motors Co.' },
  { symbol: 'GNRC', name: 'Generac Holdings Inc.' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
  { symbol: 'GPC', name: 'Genuine Parts Co.' },
  { symbol: 'GPN', name: 'Global Payments Inc.' },
  { symbol: 'GRMN', name: 'Garmin Ltd.' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.' },
  { symbol: 'HAL', name: 'Halliburton Co.' },
  { symbol: 'HAS', name: 'Hasbro Inc.' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Inc.' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.' },
  { symbol: 'HD', name: 'Home Depot Inc.' },
  { symbol: 'HOLX', name: 'Hologic Inc.' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise Co.' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'HRL', name: 'Hormel Foods Corp.' },
  { symbol: 'HSIC', name: 'Henry Schein Inc.' },
  { symbol: 'HST', name: 'Host Hotels & Resorts Inc.' },
  { symbol: 'HSY', name: 'Hershey Co.' },
  { symbol: 'HUBB', name: 'Hubbell Inc.' },
  { symbol: 'HUM', name: 'Humana Inc.' },
  { symbol: 'HWM', name: 'Howmet Aerospace Inc.' },
  { symbol: 'IBM', name: 'International Business Machines Corp.' },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc.' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
  { symbol: 'IEX', name: 'IDEX Corp.' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances Inc.' },
  { symbol: 'ILMN', name: 'Illumina Inc.' },
  { symbol: 'INCY', name: 'Incyte Corp.' },
  { symbol: 'INTC', name: 'Intel Corp.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.' },
  { symbol: 'IP', name: 'International Paper Co.' },
  { symbol: 'IPG', name: 'Interpublic Group of Companies Inc.' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc.' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.' },
  { symbol: 'IRM', name: 'Iron Mountain Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'IT', name: 'Gartner Inc.' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.' },
  { symbol: 'IVZ', name: 'Invesco Ltd.' },
  { symbol: 'J', name: 'Jacobs Solutions Inc.' },
  { symbol: 'JBHT', name: 'J.B. Hunt Transport Services Inc.' },
  { symbol: 'JCI', name: 'Johnson Controls International plc' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'JNPR', name: 'Juniper Networks Inc.' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'K', name: 'Kellanova' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'KEY', name: 'KeyCorp' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.' },
  { symbol: 'KHC', name: 'Kraft Heinz Co.' },
  { symbol: 'KIM', name: 'Kimco Realty Corp.' },
  { symbol: 'KLAC', name: 'KLA Corp.' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corp.' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.' },
  { symbol: 'KMX', name: 'CarMax Inc.' },
  { symbol: 'KO', name: 'Coca-Cola Co.' },
  { symbol: 'KR', name: 'Kroger Co.' },
  { symbol: 'KVUE', name: 'Kenvue Inc.' },
  { symbol: 'L', name: 'Loews Corp.' },
  { symbol: 'LDOS', name: 'Leidos Holdings Inc.' },
  { symbol: 'LEN', name: 'Lennar Corp.' },
  { symbol: 'LH', name: 'Labcorp Holdings Inc.' },
  { symbol: 'LHX', name: 'L3Harris Technologies Inc.' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'LKQ', name: 'LKQ Corp.' },
  { symbol: 'LLY', name: 'Eli Lilly and Co.' },
  { symbol: 'LMT', name: 'Lockheed Martin Corp.' },
  { symbol: 'LNT', name: 'Alliant Energy Corp.' },
  { symbol: 'LOW', name: 'Lowes Companies Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corp.' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.' },
  { symbol: 'LW', name: 'Lamb Weston Holdings Inc.' },
  { symbol: 'LYB', name: 'LyondellBasell Industries NV' },
  { symbol: 'LYV', name: 'Live Nation Entertainment Inc.' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'MAA', name: 'Mid-America Apartment Communities Inc.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'MAS', name: 'Masco Corp.' },
  { symbol: 'MCD', name: "McDonald's Corp." },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.' },
  { symbol: 'MCK', name: 'McKesson Corp.' },
  { symbol: 'MCO', name: "Moody's Corp." },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'MET', name: 'MetLife Inc.' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'MGM', name: 'MGM Resorts International' },
  { symbol: 'MKC', name: 'McCormick & Co. Inc.' },
  { symbol: 'MKTX', name: 'MarketAxess Holdings Inc.' },
  { symbol: 'MLM', name: 'Martin Marietta Materials Inc.' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc.' },
  { symbol: 'MMM', name: '3M Co.' },
  { symbol: 'MNST', name: 'Monster Beverage Corp.' },
  { symbol: 'MO', name: 'Altria Group Inc.' },
  { symbol: 'MOH', name: 'Molina Healthcare Inc.' },
  { symbol: 'MOS', name: 'Mosaic Co.' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corp.' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems Inc.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'MRO', name: 'Marathon Oil Corp.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'MSCI', name: 'MSCI Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corp.' },
  { symbol: 'MSI', name: 'Motorola Solutions Inc.' },
  { symbol: 'MTB', name: 'M&T Bank Corp.' },
  { symbol: 'MTCH', name: 'Match Group Inc.' },
  { symbol: 'MTD', name: 'Mettler-Toledo International Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings Ltd.' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.' },
  { symbol: 'NDSN', name: 'Nordson Corp.' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'NEM', name: 'Newmont Corp.' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'NI', name: 'NiSource Inc.' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'NOC', name: 'Northrop Grumman Corp.' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'NRG', name: 'NRG Energy Inc.' },
  { symbol: 'NSC', name: 'Norfolk Southern Corp.' },
  { symbol: 'NTAP', name: 'NetApp Inc.' },
  { symbol: 'NTRS', name: 'Northern Trust Corp.' },
  { symbol: 'NUE', name: 'Nucor Corp.' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.' },
  { symbol: 'NVR', name: 'NVR Inc.' },
  { symbol: 'NWS', name: 'News Corp. Class B' },
  { symbol: 'NWSA', name: 'News Corp. Class A' },
  { symbol: 'NXPI', name: 'NXP Semiconductors NV' },
  { symbol: 'O', name: 'Realty Income Corp.' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.' },
  { symbol: 'OKE', name: 'ONEOK Inc.' },
  { symbol: 'OMC', name: 'Omnicom Group Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.' },
  { symbol: 'ORCL', name: 'Oracle Corp.' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'OTIS', name: 'Otis Worldwide Corp.' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corp.' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'PARA', name: 'Paramount Global' },
  { symbol: 'PAYC', name: 'Paycom Software Inc.' },
  { symbol: 'PAYX', name: 'Paychex Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'PCG', name: 'PG&E Corp.' },
  { symbol: 'PEAK', name: 'Healthpeak Properties Inc.' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group Inc.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'PFG', name: 'Principal Financial Group Inc.' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'PGR', name: 'Progressive Corp.' },
  { symbol: 'PH', name: 'Parker-Hannifin Corp.' },
  { symbol: 'PHM', name: 'PulteGroup Inc.' },
  { symbol: 'PKG', name: 'Packaging Corp. of America' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'PNC', name: 'PNC Financial Services Group Inc.' },
  { symbol: 'PNR', name: 'Pentair plc' },
  { symbol: 'PNW', name: 'Pinnacle West Capital Corp.' },
  { symbol: 'POOL', name: 'Pool Corp.' },
  { symbol: 'PPG', name: 'PPG Industries Inc.' },
  { symbol: 'PPL', name: 'PPL Corp.' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.' },
  { symbol: 'PSA', name: 'Public Storage' },
  { symbol: 'PSX', name: 'Phillips 66' },
  { symbol: 'PTC', name: 'PTC Inc.' },
  { symbol: 'PVH', name: 'PVH Corp.' },
  { symbol: 'PWR', name: 'Quanta Services Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'QRVO', name: 'Qorvo Inc.' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.' },
  { symbol: 'REG', name: 'Regency Centers Corp.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'RF', name: 'Regions Financial Corp.' },
  { symbol: 'RJF', name: 'Raymond James Financial Inc.' },
  { symbol: 'RL', name: 'Ralph Lauren Corp.' },
  { symbol: 'RMD', name: 'ResMed Inc.' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.' },
  { symbol: 'ROL', name: 'Rollins Inc.' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.' },
  { symbol: 'ROST', name: 'Ross Stores Inc.' },
  { symbol: 'RSG', name: 'Republic Services Inc.' },
  { symbol: 'RTX', name: 'RTX Corp.' },
  { symbol: 'RVTY', name: 'Revvity Inc.' },
  { symbol: 'SBAC', name: 'SBA Communications Corp.' },
  { symbol: 'SBUX', name: 'Starbucks Corp.' },
  { symbol: 'SCHW', name: 'Charles Schwab Corp.' },
  { symbol: 'SHW', name: 'Sherwin-Williams Co.' },
  { symbol: 'SJM', name: 'J.M. Smucker Co.' },
  { symbol: 'SLB', name: 'Schlumberger NV' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.' },
  { symbol: 'SNA', name: 'Snap-on Inc.' },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'SO', name: 'Southern Co.' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'SRE', name: 'Sempra' },
  { symbol: 'STE', name: 'STERIS plc' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.' },
  { symbol: 'STT', name: 'State Street Corp.' },
  { symbol: 'STX', name: 'Seagate Technology Holdings plc' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.' },
  { symbol: 'SWK', name: 'Stanley Black & Decker Inc.' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.' },
  { symbol: 'SYF', name: 'Synchrony Financial' },
  { symbol: 'SYK', name: 'Stryker Corp.' },
  { symbol: 'SYY', name: 'Sysco Corp.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Co.' },
  { symbol: 'TDG', name: 'TransDigm Group Inc.' },
  { symbol: 'TDY', name: 'Teledyne Technologies Inc.' },
  { symbol: 'TECH', name: 'Bio-Techne Corp.' },
  { symbol: 'TEL', name: 'TE Connectivity Ltd.' },
  { symbol: 'TER', name: 'Teradyne Inc.' },
  { symbol: 'TFC', name: 'Truist Financial Corp.' },
  { symbol: 'TFX', name: 'Teleflex Inc.' },
  { symbol: 'TGT', name: 'Target Corp.' },
  { symbol: 'TJX', name: 'TJX Companies Inc.' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'TPR', name: 'Tapestry Inc.' },
  { symbol: 'TRGP', name: 'Targa Resources Corp.' },
  { symbol: 'TRMB', name: 'Trimble Inc.' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc.' },
  { symbol: 'TRV', name: 'Travelers Companies Inc.' },
  { symbol: 'TSCO', name: 'Tractor Supply Co.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'TSN', name: 'Tyson Foods Inc.' },
  { symbol: 'TT', name: 'Trane Technologies plc' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'TXT', name: 'Textron Inc.' },
  { symbol: 'TYL', name: 'Tyler Technologies Inc.' },
  { symbol: 'UAL', name: 'United Airlines Holdings Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.' },
  { symbol: 'UDR', name: 'UDR Inc.' },
  { symbol: 'UHS', name: 'Universal Health Services Inc.' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'UNP', name: 'Union Pacific Corp.' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.' },
  { symbol: 'URI', name: 'United Rentals Inc.' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'VICI', name: 'VICI Properties Inc.' },
  { symbol: 'VLO', name: 'Valero Energy Corp.' },
  { symbol: 'VLTO', name: 'Veralto Corp.' },
  { symbol: 'VMC', name: 'Vulcan Materials Co.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'VRSN', name: 'VeriSign Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'VST', name: 'Vistra Corp.' },
  { symbol: 'VTR', name: 'Ventas Inc.' },
  { symbol: 'VTRS', name: 'Viatris Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake Technologies Corp.' },
  { symbol: 'WAT', name: 'Waters Corp.' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'WDC', name: 'Western Digital Corp.' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc.' },
  { symbol: 'WELL', name: 'Welltower Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.' },
  { symbol: 'WM', name: 'Waste Management Inc.' },
  { symbol: 'WMB', name: 'Williams Companies Inc.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'WRB', name: 'W. R. Berkley Corp.' },
  { symbol: 'WST', name: 'West Pharmaceutical Services Inc.' },
  { symbol: 'WTW', name: 'Willis Towers Watson PLC' },
  { symbol: 'WY', name: 'Weyerhaeuser Co.' },
  { symbol: 'WYNN', name: 'Wynn Resorts Ltd.' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corp.' },
  { symbol: 'XRAY', name: 'DENTSPLY SIRONA Inc.' },
  { symbol: 'XYL', name: 'Xylem Inc.' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc.' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corp.' },
  { symbol: 'ZION', name: 'Zions Bancorporation NA' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },
];

// Build a deduplicated master list with index membership tags
export function buildMasterList() {
  const map = new Map();

  for (const entry of DJIA) {
    map.set(entry.symbol, { ...entry, indexes: ['DJIA'] });
  }
  for (const entry of NASDAQ100) {
    if (map.has(entry.symbol)) {
      map.get(entry.symbol).indexes.push('NASDAQ-100');
    } else {
      map.set(entry.symbol, { ...entry, indexes: ['NASDAQ-100'] });
    }
  }
  for (const entry of SP500) {
    if (map.has(entry.symbol)) {
      map.get(entry.symbol).indexes.push('S&P 500');
    } else {
      map.set(entry.symbol, { ...entry, indexes: ['S&P 500'] });
    }
  }

  return Array.from(map.values()).sort((a, b) =>
    a.symbol.localeCompare(b.symbol)
  );
}
